const ACTION_TYPE = {
  DEFAULT_VIDEO: "DEFAULT_VIDEO",
  WATCHLATER_VIDEO: "WATCHLATER_VIDEO",
  REMOVE_WATCHLATER_VIDEO: "REMOVE_WATCHLATER_VIDEO",
  PLAYLIST: "PLAYLIST",
  SINGLE_PLAYLIST: "SINGLE_PLAYLIST",
  VIDEO_TO_PLAYLIST: "VIDEO_TO_PLAYLIST",
  DELETED_VIDEO: "DELETED_VIDEO",
  SINGLE_VIDEO: "SINGLE_VIDEO",
  LIKED_VIDEO: "LIKED_VIDEO",
  REMOVE_LIKED_VIDEO: "REMOVE_LIKED_VIDEO",
};

export { ACTION_TYPE };
